# GitHub Pages Configuration
# This file configures GitHub Pages to serve clean URLs

# Site settings
title: "Mikkel Hansen - Men's Development Coach"
description: "Breaking free from default mode patterns. Transform from boy to man through authentic self-discovery."
url: "https://mikkelhansen.org"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Permalinks - this removes .html from URLs
permalink: /:title/

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include
include:
  - _redirects

# Plugins
plugins:
  - jekyll-redirect-from
